export class NewCBHomepage{
    constructor(){
        this.elements={
            NewContentBrief: ()=> cy.get('#content-brief-new'),
            SelectedLocale: ()=> cy.get('div[class*="flag-icon"]+div'),
            AddkeywordBtn: ()=> cy.get('#add-keyword_button'),
            GenerateBriefBtn: ()=> cy.get('#submit-btn_button'),
            CancelBtn:()=> cy.get('#cancel_cb_button'),
            AddKWField:()=> cy.get('#keyword_input_keyword'),
            KWRemovebtn:()=>cy.get('div[id="breadcrumb"] +div>div:nth-child(2) label+div'),
            RemoveAllbtn:()=>cy.get('div[id="breadcrumb"] +div>div:nth-child(2) button>span'),
            KWvalidationtext:()=>cy.get('div[id="keyword_input_keyword_inputError"]>div'),
            SuggestedKeywordtab:()=>cy.get('div[id="breadcrumb"] +div>div:nth-of-type(3)>div>span:nth-child(1)'),
            InputKeywordtab:()=>cy.get('div[id="breadcrumb"] +div>div:nth-of-type(3)>div>span:nth-child(2)'),
            SuggestedKeywordscheckbox:()=>cy.get('input[id*=related_kw_checkbox]'),
            suggestedkwstext:()=>cy.get('input[id*=related_kw_checkbox]+span'),
            Notificationmessage:()=>cy.get('#version_notification_message>div'),
            FirstKWSV:()=>cy.get('#kw_table_body>div:nth-of-type(1)>div:nth-of-type(2)'),
            FirstSuggestedKW:()=>cy.get('#kw_table_body>div:nth-of-type(1) input[type="checkbox"]'),
            SelectedKW:()=>cy.get('div[id="breadcrumb"] +div>div:nth-child(2) label'),
            SVFilter:()=>cy.get('#kw_url_search-volume_title'),
            RelevanceScoreFilter:()=>cy.get('#kw_url_relevance-score_title'),
            ThousandtoLacFilter:()=>cy.get('input[id="kw_url_project_filter_10-001-100-000"]'),
            FilteredSV:()=>cy.get('div#kw_table_body>div>div:nth-child(2)'),
            defaultselectedKW:()=>cy.get('div[id="breadcrumb"] +div>div:nth-child(2)>div label'),
            fivetosevenrelevancescore:()=>cy.get('input[id="kw_url_project_filter_0-5-0-7"][type="checkbox"]'),
            FilteredRelevancescore:()=>cy.get('div#kw_table_body>div>div:nth-of-type(3)'),
            SuggestedKWsearchbar:()=>cy.get('#kw_related_filter_search_input'),
            SuggestedKWnames:()=>cy.get('input[id*=related_kw_checkbox] +span'),
            ShowAllbtn:()=>cy.get('div[id="cb_keyword_list"]+div>div>span'),
            PopupOKBtn:()=>cy.get('#ok-btn_button'),
            PopupdownloadBtn:()=>cy.get('#download_submit_button',{timeout:600000}),
            PopupViewBtn:()=>cy.get('#view_content_brief_button',{timeout:600000}),
            Popsuccessmessage:()=>cy.get('#generate_brief_modal-body>div>div'),
            Popupclosebtn:()=>cy.get('#generate_brief_modal-body>div>button'),
            SuggestedKeywordtable:()=>cy.get('#kw_table_body'),
            Keywordsortingbtn:()=>cy.get('div[id="breadcrumb"] +div>div:nth-of-type(4)>div>div:nth-of-type(2) label:nth-of-type(1)+div>div:nth-child(1)'),
            Searchvolumesortingbtn:()=>cy.get('div[id="breadcrumb"] +div>div:nth-of-type(4)>div>div:nth-of-type(2)>div>div:nth-of-type(2)>div>div:nth-of-type(2)>div:nth-of-type(1)'),
            RelevanceScoresortingbtn:()=>cy.get('div[id="breadcrumb"] +div>div:nth-of-type(4)>div>div:nth-of-type(2)>div>div:nth-of-type(3)>div:nth-of-type(1)>div:nth-of-type(2)>div:nth-of-type(1)'),
            SuggestedkeywordSearchvolumes:()=>cy.get('div[id="kw_table_body"]>div>div+div:nth-of-type(2)'),
            SuggestedKeywordRelevance:()=> cy.get('div[id="kw_table_body"]>div>div+div:nth-of-type(3)')
        }
    }
}
export const  newcb =new NewCBHomepage();