/* eslint-disable cypress/no-unnecessary-waiting */
describe('As a Project user', () => {
    beforeEach(() => {
        cy.loginUser('Iquanti Training')
        cy.restoreLocalStorage()
    })
    afterEach(() => {
        cy.saveLocalStorage()
    })
    it('verify Reports homepage - Dashboard', () => {
        // eslint-disable-next-line cypress/no-unnecessary-waiting
        cy.wait(7000)
        cy.get('div#root header div div:nth-child(2) nav div:nth-child(3)').click()
        cy.wait(2000)
        cy.get('div.showMenu nav a:nth-child(1)').click()
        cy.get('div.filter_left_coloum').should('be.visible')
        cy.get('div.filter_right_coloum').should('be.visible')
        cy.get('div.download_button.bottom').should('be.visible')
        cy.get('div.mainButton.pull-right.ng-scope').should('be.visible')
        cy.get('div.rank_distribution.clearfix h2').contains('Rank Distribution of Keywords').should('be.visible')
        cy.get('div#rankDistribution div div svg').should('be.visible')
        cy.get('div.selection_button div:nth-child(2) button').click()
        cy.wait(2000)
        cy.get('div#rankDistribution div div svg').should('be.visible')
        cy.get('div.selection_button div:nth-child(3) button').click()
        cy.wait(2000)
        cy.get('div#rankDistribution div div svg').should('be.visible')
        cy.get('div.rank_distribution.shareOfSearch h2').should('have.text', 'Share of Search of Non-Branded Keywords')
        cy.get('div.sos_chart div div svg').should('be.visible')
        cy.get('div.rank_distribution.traffic_report h2').should('have.text', 'Organic Keyword Traffic')
        cy.get('div.traffic_chart div div svg').should('be.visible')
        cy.get('div.top_gainers').should('be.visible')
        cy.get('div.top_losers').should('be.visible')
        cy.get('div.perf-traf').should('be.visible')
        cy.get('div.perf-conver').should('be.visible')
        cy.get('div.perf-sales').should('be.visible')
        cy.get('div.perform-tab').should('be.visible')
    })
    it('verify Reports homepage - Keywords', () => {
        // eslint-disable-next-line cypress/no-unnecessary-waiting
        cy.wait(7000)
        cy.get('div#root header div div:nth-child(2) nav div:nth-child(3)').click()
        cy.wait(2000)
        cy.get('div.showMenu nav a:nth-child(1)').click()
        cy.get('div.report_container ul li:nth-child(3) a').click()
        cy.get('div.top_title h2').should('have.text', 'Keywords - Rank & Performance')
        cy.get('div.filter_left_coloum').should('be.visible')
        cy.get('div.filter_right_coloum').should('be.visible')
        cy.get('div.download_button.bottom').should('be.visible')
        cy.get('div.mainButton.pull-right.ng-scope').should('be.visible')
        cy.get('div.main_detailsData').should('be.visible')
        cy.get('div.main_tableHead div.col_1 span').should('contain.text', 'Keyword')
        cy.get('span#col_weighted_offpage_score_sort').should('contain.text', 'Rank')
        cy.get('span#col_total_backlinks_sort').should('contain.text', 'Traffic')
        cy.get('span#col_unique_domains_sort').should('contain.text', 'Conversions')
        cy.get('span#col_unique_domains_sort').should('contain.text', 'Sales Completions')
    })
    it('verify Reports homepage - Themes', () => {
        // eslint-disable-next-line cypress/no-unnecessary-waiting
        cy.wait(7000)
        cy.get('div#root header div div:nth-child(2) nav div:nth-child(3)').click()
        cy.wait(2000)
        cy.get('div.showMenu nav a:nth-child(1)').click()
        cy.get('div.report_container ul li:nth-child(4) a').click()
        cy.get('div.top_title h2').should('have.text', 'Themes - Rank & Performance')
        cy.get('div.filter_left_coloum').should('be.visible')
        cy.get('div.filter_right_coloum').should('be.visible')
        cy.get('div.download_button.bottom').should('be.visible')
        cy.get('div.main_table').should('be.visible')
        cy.get('div.main_tableHead').should('be.visible')
        cy.get('div.main_tableHead div.col_1 span').should('contain.text', 'Theme')
        cy.get('div.main_tableHead div.col_2.rank span').should('contain.text', 'Rank')
        cy.get('div.main_tableHead div.col_3 span').should('contain.text', 'Competitor Rank')
        cy.get('div.main_tableHead div.col_2.traffic span').should('contain.text', 'Traffic')
        cy.get('div.main_tableHead div.col_2 span').contains('Conversions')
        cy.get('div.main_tableHead div.col_2 span').contains('Sales Completions')
    })
    it('verify Reports homepage - Competition', () => {
        // eslint-disable-next-line cypress/no-unnecessary-waiting
        cy.wait(7000)
        cy.get('div#root header div div:nth-child(2) nav div:nth-child(3)').click()
        cy.wait(2000)
        cy.get('div.showMenu nav a:nth-child(1)').click()
        cy.get('div.report_container ul li:nth-child(5) a').click()
        cy.get('div.top_title h2').should('have.text', 'Competition - Share Of Search & Rank Distribution')
        cy.get('div.filter_left_coloum').should('be.visible')
        cy.get('div.filter_right_coloum').should('be.visible')
        cy.get('div.download_button.bottom').should('be.visible')
        cy.get('div.pull-right.mainButton.keybttn.back').should('be.visible')
        cy.get('div.main_tableHead.main_detailsHead').should('be.visible')
        cy.get('div.main_table.main_detailsHeadTab').should('be.visible')
        cy.get('div.main_table').should('be.visible')
        cy.get('div.main_tableHead div.col_1 span').should('contain.text', 'Domain')
        cy.get('div.main_tableHead div.col_2 span').should('contain.text', 'Non-Branded Share of Search')
        cy.get('div.main_tableHead div.col_2.comp_graph span').should('contain.text', 'Non-Branded Rank Distribution')
    })
})
