import * as kgaAction from '../../../../pages/commands/kgahomepage'
import * as simAction from '../../../../pages/commands/simulation'

describe('As a KGA user', () => {
    before(() => {
        cy.loginUser()
    })
    beforeEach(() => {
        cy.restoreLocalStorage()
    })
    afterEach(() => {
        cy.saveLocalStorage()
    })
    it('verify KGA homepage', () => {
        kgaAction.validateInputKeywordField()
        kgaAction.validateInputUrlField()
    })
    it('verify SERP page', () => {
        kgaAction.enterKeyword('Car speed')
        kgaAction.enterURL('https://www.allstate.com/')
        kgaAction.clickGo()
        kgaAction.validateResultsPage()
        kgaAction.validateDomainRankLabel()
        kgaAction.validateSerpTableHeaderTopRankingUrls()
        kgaAction.validateSerpKgaButton()
        kgaAction.validateSerpSimulationButton()
    })
    it('verify KGA page', () => {
        kgaAction.clickSerpKgaButton()
        kgaAction.validateKgaPage()
        kgaAction.validateKgaComparisonLabel()
        kgaAction.validateKgaHighestRankLabel()
        kgaAction.validatekgaSerpPacksLabel()
        kgaAction.validatekgaKeywordPerformanceLabel()
        kgaAction.validateKgaContentScoreLabel()
        kgaAction.validateKgaSeoParameterLabel()
        kgaAction.validateKgaParameterGroupsContainer()
        kgaAction.validateKgaViewTop10CompetitorsLink()
        kgaAction.clickKgaViewTop10CompetitorsLink()
        kgaAction.validateKgaModalTop10CompetitorScoresTitle()
        kgaAction.clicKgaModalCloseButton()
    })
    it('verify Simulation page from SERP page', () => {
        kgaAction.navigateBack()
        kgaAction.clickSerpSimulationButton()
        simAction.validateSimulationTitle()
        simAction.clickProceedToSimulationButton()
        simAction.validateSimulationUrlLabel()
        simAction.validateKeywordLevelImpactLink()
        simAction.validateTrafficAndRankLink()
        simAction.validateEditorContainer()
        simAction.validateScoresContainer()
        simAction.validateRunSimulationButton()
        simAction.validateDownloadButton()
        simAction.clickKeywordLevelImpactLink()
        simAction.validateKeywordLevelImpactModalTitle()
        simAction.validateKeywordLevelImpactModalTable()
        simAction.clickKeywordLevelImpactModalCloseButton()
        simAction.clickZoomModeButton()
        simAction.validateEditorContainer()
        simAction.validateZoomModeScoresContainer()
        simAction.validatezoomModeKeywordImpactContainer()
        simAction.validateViewOriginalButton()
        simAction.clickZoomModeButton()
        simAction.editTitle()
        simAction.clickRunSimulationButton()
        simAction.validateEditorContainer()
        simAction.validateScoresContainer()
        simAction.validateRunSimulationButton()
    })
})
