/* eslint-disable cypress/no-unnecessary-waiting */
describe('As a Project user', () => {
    beforeEach(() => {
        cy.loginUser('Iquanti Inc', 2)
        cy.restoreLocalStorage()
    })
    afterEach(() => {
        cy.saveLocalStorage()
    })
    it('verify Audits homepage - Content Gap Analysis', () => {
        cy.wait(7000)
        cy.get('div#root header div div:nth-child(2) nav div:nth-child(3)').click()
        cy.wait(2000)
        cy.get('div.showMenu nav a:nth-child(2)').click()
        cy.get('div.top_title h2').should('have.text', 'Content Gap Analysis')
        cy.get('div.filter_left_coloum').should('be.visible')
        cy.get('div.filter_right_coloum').should('be.visible')
        cy.get('div.download_button.bottom').should('be.visible')

        cy.get('div.main_tableHead').should('be.visible')
        cy.get('div.main_table').should('be.visible')
        cy.get('div.main_tableHead div.col_1 span').should('contain.text', 'Theme')
        cy.get('div.main_tableHead div.col_2 span').contains('Rank')
        cy.get('div.main_tableHead div.col_2 span').contains('Content Score')
        cy.get('div.main_tableHead div.col_2.main_tableHead_dropdown span:nth-child(1)').should('contain.text', 'Traffic')
        cy.get('div.main_tableHead div.col_3 span').should('contain.text', 'Recommendations')
    })
    it('verify Audits homepage - Backlink Analysis', () => {
        cy.wait(7000)
        cy.get('div#root header div div:nth-child(2) nav div:nth-child(3)').click()
        cy.wait(2000)
        cy.get('div.showMenu nav a:nth-child(2)').click()
        cy.get('div.audit_container ul li:nth-child(3) a').click()
        cy.get('div.main_bdy_subcontainer div:nth-child(2) div div').contains('Backlink Analysis')
        cy.get('div.col-lg-2.col-md-3.col-sm-4.col-xs-6.pd0.font14').contains('Perform analysis for')
        cy.get('button#menu1').should('be.visible')
        cy.get('button').contains('Analyze')
    })
    it('verify Audits homepage - Tech Audit', () => {
        cy.wait(7000)
        cy.get('div#root header div div:nth-child(2) nav div:nth-child(3)').click()
        cy.wait(2000)
        cy.get('div.showMenu nav a:nth-child(2)').click()
        cy.get('div.audit_container ul li:nth-child(4) a').click()
        cy.get('h1').contains('Technical Audit Overview')
        cy.get('button#downshift-0-input').should('be.visible')
        cy.get('button#downshift-1-input').should('be.visible')
        cy.get('h2').contains('Page Crawled')
        cy.get('h2').contains('Issues Found')
        cy.get('h2').contains('Issues Categories')
        cy.get('h2').contains('Most Occurring Issues')
        cy.get('h2').contains('IMPORTANT TECHNICAL CHECKS')
    })
})
